version: "3.3"
services:   
  server:
    container_name: "server"
    build: server
    ports:
      - "9000:9000"
    env_file:
      - "./server/.env.sample"
    network_mode: host
      
  client:
    container_name: "client"
    build: client
    ports:
      - "3000:3000"
    depends_on: 
      - server
    network_mode: host
